# ===============================
# CONFIGURACIÓN GENERAL
# ===============================

# Nombre de la aplicación
spring.application.name=inventory

# Puerto donde corre el backend
server.port=8080


# ===============================
# BASE DE DATOS (POSTGRESQL)
# ===============================

# URL de conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db

# Usuario de PostgreSQL
spring.datasource.username=postgres

# Contraseña de PostgreSQL
spring.datasource.password=123456

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================

# IMPORTANTE:
# validate = verifica que las tablas existan
# NO crea tablas (eso lo hace Liquibase)
spring.jpa.hibernate.ddl-auto=validate

# Muestra las consultas SQL en consola
spring.jpa.show-sql=true

# Formatea el SQL para que sea legible
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# LIQUIBASE (REEMPLAZA FLYWAY)
# ===============================

# Activa Liquibase
spring.liquibase.enabled=true

# Ruta del archivo principal de migraciones
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
logging.level.liquibase=INFO

# ===============================
# LOGS (opcional pero PRO)
# ===============================

# Muestra queries SQL más detalladas
logging.level.org.hibernate.SQL=DEBUG

# Muestra valores de parámetros en SQL
logging.level.org.hibernate.type.descriptor.sql=TRACE